import {Lesson,checks,eq,sec} from './types';
export const extensions:Lesson[]=[
{id:'external-demand',part:'extensions',title:'Connect an external demand model without double counting',summary:'A safe first bridge from bottom-up services to SWITCH’s electrical loads.',goals:['Choose replacement, addition or decomposition explicitly.','Preserve annual energy, peak and temporal alignment.','Distinguish a data link from endogenous demand optimization.'],sections:[
sec('Define the handoff contract',['An external demand model can produce annual electricity, hourly profiles, useful-energy service or equipment-specific consumption. SWITCH’s base demand input expects electrical power by load zone and timepoint. State the transformation between those outputs and zone_demand_mw before joining tables.','For residential heating/cooling, useful thermal energy is not electricity. Convert with a defensible efficiency or COP profile, preserving weather dependence when important. For district systems or combined heat and power, the interface may require additional networks and service balances rather than one electrical-load column.']),
sec('Do not add a sector twice',['If baseline demand already includes households, adding a full new residential profile double-counts them. Choose one of three contracts: replace total load; replace a measured sectoral component while retaining the residual; or add only a genuinely incremental service not already included.'],[eq(String.raw`D^{\mathrm{new}}_{z,t}=D^{\mathrm{baseline}}_{z,t}-D^{\mathrm{old\ sector}}_{z,t}+D^{\mathrm{new\ sector}}_{z,t}`,'A sector-replacement contract. The old component must be estimated consistently; subtracting an unrelated profile can create negative residual demand.'),eq(String.raw`D^{\mathrm{new}}_{z,t}=D^{\mathrm{baseline}}_{z,t}+\Delta D^{\mathrm{incremental}}_{z,t}`,'An incremental contract. ΔD is the change beyond what the baseline already represents, not the entire future sector.')]),
sec('Map geography and time with conservation checks',['Map buildings or regions to load zones using transparent shares. Keep the total invariant when aggregating. Align timezone, timestamp, weather year and leap-day handling with renewable profiles. Aggregate high-resolution power into timepoint-average MW before annual representation is applied.','If an annual sector demand E is distributed using a raw nonnegative shape q_t, normalize it with the actual model weights: D_t = E q_t / Σ(q_t w_t). Then check both annual energy and the resulting peak. A shape built from representative extremes can match annual energy while exaggerating or suppressing peak.']),
sec('Soft linking versus endogenous decisions',['One-way linking supplies demand and leaves SWITCH to choose supply. An iterative soft link can pass electricity prices or emissions back to the demand model and update demand, but convergence, double counting and the meaning of planning-model prices need attention. Endogenous equipment adoption or comfort-constrained flexibility requires new variables, costs and service equations.','Your residential model remains an optional idea. Use this interface pattern for any defensible external load—industry, EVs, data centres or water systems—without assuming one is already selected as the research topic.'])],worked:{title:'Replace only the residential component',setup:'At a specific timepoint, baseline total load is 100 MW, the old residential component is 30 MW and the new bottom-up estimate is 45 MW.',steps:['Residual non-residential load = 100 − 30 = 70 MW.','New total = 70 + 45 = 115 MW, not 145 MW.','Repeat the operation on aligned timepoints and check nonnegative residuals.','Recompute annual demand, peak and load factor using the model weights; archive the old-sector estimate and transformation.'],result:'The meaningful change is +15 MW at this point, not the full 45 MW new residential estimate.'},pitfalls:['Adding total household consumption to a baseline that already contains it.','Converting annual demand to a flat profile when coincidence with weather is central to the question.'],checks:checks(['Is an external fixed profile a new endogenous decision variable?','No. It is a data input unless the formulation explicitly allows demand or equipment choices to change.'],['What denominator normalizes raw shape q to annual MWh E?','The weighted sum Σ q_t w_t; this ensures Σ D_t w_t = E.'],['What makes an iterative price–demand link difficult?','Planning prices can require scaling and interpretation; discrete decisions and non-smooth responses can prevent convergence; welfare and cost boundaries must remain consistent.']),sources:['zones','time','workbench']},
{id:'write-extension',part:'extensions',title:'Write a small module and test every connection',summary:'A concrete Pyomo/SWITCH example with a physical service requirement.',goals:['Recognize a minimal extension’s model hooks.','Link a flexible electric task to service, balance and cost.','Design parity and infeasibility tests before national use.'],sections:[
sec('Start with a tiny, explicit service',['Consider an already installed flexible electrical process. It must consume a specified amount of electricity in each representative timeseries and cannot exceed a supplied power limit. This is a teaching example for task scheduling, not a calibrated building, EV or hydrogen model. Its power capacity is an input; it does not choose new equipment.','The process can shift across the steps of its series, but not move service freely between seasons. The service requirement uses physical time-step durations. Repetition weights belong to annual operating-cost and energy accounting.']),
{title:'An educational module skeleton',paragraphs:['Save and activate an extension like this only in a separate development branch after creating its inputs and tests. It is shown for learning; it is not an enabled workbench feature. This skeleton assumes service can be scheduled anywhere within each timeseries and has no additional state or efficiency loss.'],code:`from pyomo.environ import Set, Param, Var, Expression, Constraint, NonNegativeReals
import os

dependencies = (
    "switch_model.timescales",
    "switch_model.financials",
    "switch_model.balancing.load_zones",
)

def define_components(m):
    m.TASK_ZONES = Set(within=m.LOAD_ZONES)
    m.task_power_limit_mw = Param(m.TASK_ZONES, within=NonNegativeReals)
    m.task_cost_per_mwh = Param(m.TASK_ZONES, within=NonNegativeReals)
    m.task_energy_mwh = Param(m.TASK_ZONES, m.TIMESERIES, within=NonNegativeReals)
    m.TaskPower = Var(m.LOAD_ZONES, m.TIMEPOINTS, within=NonNegativeReals,
        bounds=lambda m, z, t: (0, m.task_power_limit_mw[z])
            if z in m.TASK_ZONES else (0, 0))
    m.TaskService = Constraint(m.TASK_ZONES, m.TIMESERIES,
        rule=lambda m, z, ts: sum(
            m.TaskPower[z, t] * m.tp_duration_hrs[t]
            for t in m.TPS_IN_TS[ts]) == m.task_energy_mwh[z, ts])
    m.Zone_Power_Withdrawals.append("TaskPower")
    m.TaskOperatingCost = Expression(m.TIMEPOINTS,
        rule=lambda m, t: sum(m.TaskPower[z, t] * m.task_cost_per_mwh[z]
            for z in m.TASK_ZONES))
    m.Cost_Components_Per_TP.append("TaskOperatingCost")

def load_inputs(m, switch_data, inputs_dir):
    switch_data.load_aug(filename=os.path.join(inputs_dir, "task_zones.csv"),
        index=m.TASK_ZONES,
        param=(m.task_power_limit_mw, m.task_cost_per_mwh))
    switch_data.load_aug(filename=os.path.join(inputs_dir, "task_energy.csv"),
        param=(m.task_energy_mwh,))`},
sec('What each connection does',['TaskPower spans all zones so the standard balance can retrieve [z,t] safely. Zones outside TASK_ZONES have a zero upper bound. TaskService requires the process to do its work. The withdrawal registration makes electricity supply respond. TaskOperatingCost is currency/hour, so the standard financial module weights it exactly once.','The input tables need unique zone and zone/timeseries keys with complete coverage. Add reporting that exports TaskPower and independently sums physical service and weighted annual electricity. Decide whether the new load belongs in planning-reserve requirements; that is not automatically resolved by its energy-balance registration.']),
sec('Test the edge cases',['Use a one-zone, two-step case with known electricity costs. Check zero service reproduces the baseline, scheduling respects the power limit, total service is conserved, impossible service becomes infeasible, and cost scales with the supplied price. Check zones without the process remain unchanged.','Before real use, add validated service-specific availability, losses, capacity investment or thermal states as needed. Do not deploy a national extension simply because this skeleton imports successfully.'])],worked:{title:'A hand-solvable scheduling test',setup:'Two one-hour steps cost 20 and 80 currency/MWh to supply. A flexible task needs 4 MWh and has a 3 MW power limit, with zero additional process cost.',steps:['The cheapest feasible schedule uses 3 MW in the first step and 1 MW in the second.','Service delivered is 3 × 1 + 1 × 1 = 4 MWh.','Electricity cost is 3 × 20 + 1 × 80 = 140 currency for the physical block.','A request for 7 MWh is infeasible because the two-step maximum is 6 MWh.'],result:'A tiny expected answer checks the physical and economic integration more effectively than a large opaque run.'},pitfalls:['Allowing a new component to consume electricity outside the registered power balance.','Confusing the executable teaching skeleton with a tested, production-ready sector module.'],checks:checks(['Why is TaskPower defined for zones without the process?','The zonal registry expects a value at every zone/timepoint. Fixed-zero bounds provide a safe zero contribution.'],['Which weights enforce the task’s within-series energy requirement?','Physical tp_duration_hrs, not tp_weight_in_year.'],['What additional equation would be needed for a temperature-constrained building?','A thermal state/heat-balance relation with comfort bounds and conversion/availability constraints, calibrated to the building/service representation.']),sources:['zones','finance','time','pyomo']},
{id:'new-country',part:'extensions',title:'Build a new country or regional SWITCH application',summary:'A practical data-and-model roadmap that transfers beyond Kenya.',goals:['Choose geography and decisions appropriate to the question.','Build a coherent baseline before testing future policies.','Understand regional coordination and institutional limits.'],sections:[
sec('Start from the question’s resolution',['For a Saudi or GCC study, a single zone may be adequate for a narrowly scoped national energy-mix experiment but inadequate for congestion, cross-border sharing or county-level justice. Define the smallest geography that preserves the mechanisms relevant to the question. More zones are not automatically better if their data is weak.','Decide whether investment is centrally coordinated, nationally constrained or selected by separate actors. A least-cost regional planner is a useful counterfactual, but not a prediction that governments or utilities will implement its plan. Institutional agreements, cost allocation and trade rules require explicit assumptions or complementary analysis.']),
sec('Build the baseline data package',['Assemble spatial demand with a consistent temporal profile, existing project vintages, candidate technologies and costs, fuel prices and supply limits, renewable profiles, hydro/water assumptions where relevant, storage, corridors and policy constraints. Record source year and transformation for each item.','Use atlas data to orient the study and compare totals, not as a complete automatic model generator. Annual energy statistics, installed-capacity inventories and electricity prices often have different years and boundaries. A project inventory is not a validated hourly generation profile or a dispatchable capacity assumption.']),
sec('Separate physical and institutional restrictions',['A cross-border corridor may have physical MW capability but not unlimited commercial access. Model losses, availability, trade limits and expansion permissions explicitly. If imports are from outside the model, define price and availability rather than treating them as a costless balancing resource.','Regional cooperation can create aggregate savings with uneven country benefits. Compare coordinated and restricted cases using matched assumptions, then examine country costs, exports/imports, reliability and emissions. Designing transfers or market settlements is a separate modelling question.']),
sec('A disciplined build order',['First create a one-zone baseline with hand-checked data and annual totals. Add spatial zones and verify transfers. Add storage and chronology. Add the policy or new demand mechanism central to the research. Introduce uncertainty after deterministic parity is established.','At every stage, use source pins, small test cases, a change log and fixed-plan validation. Transfer mathematical ideas from Kenya while re-evaluating country-specific assumptions such as fuel availability, load shape, resource quality, reserve credit and investment limits.'])],worked:{title:'Measure the modelled value of regional coordination',setup:'Two regions can expand generation separately or coordinate through a proposed corridor.',steps:['Solve a no-new-trade baseline with matching demand and costs.','Allow the proposed corridor with realistic cost, losses and transfer constraints.','Compare total cost and regional outcomes, including whose generation and imports change.','Stress fuel, demand and corridor availability; evaluate any country-specific service constraints.','Describe savings as conditional planner-model benefits, not guaranteed commercial revenues.'],result:'A regional model can reveal opportunities without assuming institutions, contracts or cost sharing already exist.'},pitfalls:['Copying Kenya’s county, fuel or reserve assumptions into another country unchanged.','Interpreting cooperative-planner savings as evidence that all parties benefit equally.'],checks:checks(['Can the atlas alone produce a research-ready country model?','No. It provides sourced context, but detailed profiles, project assumptions, network data and validation are still required.'],['What is held constant in a clean interconnection comparison?','Demand, technology and fuel assumptions, financial horizon, source version and relevant policy/adequacy assumptions, except for the intended network change.'],['Why might a regionally optimal plan be politically difficult?','Costs, benefits, dependence and risks may be distributed unevenly, and the optimization may omit bargaining, sovereignty or commercial constraints.']),sources:['atlas','txBuild','txDispatch','kenyaData','workbench']},
{id:'capstone',part:'extensions',title:'Capstone: become comfortable enough to question the model',summary:'A complete practice path from a tiny balance to a defensible extension proposal.',goals:['Demonstrate mathematical and operational understanding.','Build an evidence-backed experiment portfolio.','Know what remains unverified and what to study next.'],sections:[
sec('Your eight-part practical portfolio',['Work through the tasks below in order. Write a prediction before each experiment, retain the run/input identity, then explain the observed result. Use the local workbench for solver tasks; the browser calculators are illustrative only.'],undefined,['1. Units: reconstruct annual demand, a generation capacity factor and storage duration from a small dataset. Explain every denominator.','2. Dispatch: solve the two-generator example by hand and identify what breaks merit order when a network or minimum-load restriction is introduced.','3. Finance: independently reproduce an annual capital charge and a multi-year objective contribution, including the zero-rate case.','4. Tutorial: reproduce the pinned baseline, duplicate it with demand ×1.2, and explain changes in builds, dispatch and cost—not just the objective.','5. Physical stress: evaluate a candidate fleet under a low-renewable sequence; show how storage state and firm availability affect feasibility.','6. Kenya audit: map one county, one generator, one corridor and one technology build limit; state the exact active module list and verification status.','7. Uncertainty: calculate RP, EEV, WS, VSS and EVPI for the hand example; explain why independent reoptimization has perfect information.','8. Extension design: propose one optional new sector or constraint with input contract, equations, cost registration, tests, data gaps and a zero-effect parity condition.']),
sec('What a strong explanation contains',['For each result, state the research question, system boundary, exogenous assumptions, decision variables, objective, active constraints, units, source version and solve status. Then give the mechanism: which constraints bind, how operation changes and what investment trade-off follows.','Explain at least one alternative interpretation and one limitation. A convincing modeller can say both what the result supports and what would require another model, dataset or experiment.']),
sec('A readiness checklist',['You are ready to extend the model when you can trace a parameter from its input file to an equation, predict a small perturbation, identify a decision’s index and unit, reconstruct weighted totals, and diagnose a failed run without immediately changing random solver settings.','You do not need to memorize every source file. Knowing where an equation lives and how to verify it is more useful. Keep the variable dictionary and source map open while reading code. Revisit the worked examples whenever a MW/MWh or annual/period distinction becomes unclear.']),
sec('Advanced territory beyond this foundation',['The course covers the core planning workflow and major extension concepts; it is not documentation for every optional SWITCH module or a complete power-system engineering textbook. Depending on the research question, continue into detailed hydro and river networks, operating reserves, fuel supply curves, distributed resources, endogenous technology adoption, multistage stochastic decomposition, robust optimization, AC/DC security validation or welfare/market design.','For each advanced topic, first verify the active implementation and its compatibility with the pinned framework. Do not assume a conceptual lesson or an available upstream module is already integrated into this workbench.'])],worked:{title:'A one-page extension brief',setup:'Pick one idea—for example flexible industrial load, weather-sensitive cooling, a regional transfer rule or a new emissions budget.',steps:['Question: what decision or trade-off cannot the present model answer?','Boundary: what geography, timescale, service and economic perspective are required?','Mathematics: list new inputs, variables, constraints and objective contributions with units.','Integration: identify power, costs, reliability and reporting connections.','Evidence: list data sources, calibration/validation tests, zero-effect parity and known limitations.','Experiment: define baseline, one controlled alternative and an uncertainty/stress evaluation.'],result:'A bounded, testable extension brief is a stronger starting point than a long list of unconnected features.'},pitfalls:['Equating finishing lessons with validation of a national model.','Adding complexity before identifying the decision it needs to improve.'],checks:checks(['What should always accompany an optimization result?','Its assumptions/boundary, input and source identity, status, relevant units and verification limits.'],['What is the minimum useful test for a new module?','A small case with a known answer plus a zero-effect parity case; add physical, economic and edge-case checks before scaling.'],['How do you know whether more model detail is worthwhile?','Ask whether it could change the decision or invalidate the conclusion, whether suitable data exists, and whether an independent validation model can answer the need more efficiently.']),sources:['core','verification','workbench']}
];
