'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ArrowDownToLine,ArrowUpRight,Check,ChevronDown,Database,Globe2,Info,LoaderCircle,Search,X} from 'lucide-react';
import type {Atlas,Country,Histories,IndicatorMeta,Observation,PowerAsset} from './types';
import AtlasCountryPanel from './atlas-country-panel';
import {compact,number} from './types';
import {commonMix,comparisonObservation,displayUnit,fetchAtlasJSON,makeCSV,observationCSV,periodOf,seriesFor,transformedSeries} from './atlas-state';
const Globe=dynamic(()=>import('./globe'),{ssr:false,loading:()=> <div className="globe-panel map-loading"><LoaderCircle className="spin"/> Loading globe</div>});
const colors=['#2889d7','#df9950','#8c76c8','#2ba389','#d27999','#6e8eaa'];
const tooltip={background:'rgba(255,255,255,.96)',border:'1px solid #d9e1e8',borderRadius:14,color:'#172d3e',boxShadow:'0 12px 36px #17364718'};
const generationKeys=['generation_coal','generation_gas','generation_other_fossil','generation_nuclear','generation_hydro','generation_wind','generation_solar','generation_bioenergy','generation_other_renewables'];
const capacityKeys=['capacity_coal','capacity_gas','capacity_oil','capacity_nuclear','capacity_hydro_renewable','capacity_hydro_mixed','capacity_wind_onshore','capacity_wind_offshore','capacity_solar_pv','capacity_csp','capacity_bioenergy','capacity_geothermal'];
function valueText(o:Observation|undefined){return typeof o?.value==='string'?o.value:o?.value==null?'No data':number(o.value,3);}
function saveFile(text:string,name:string,type='text/csv;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function CountrySearch({countries,selected,onSelect,label='Country'}:{countries:Country[];selected?:string;onSelect:(iso:string)=>void;label?:string}){
 const [q,setQ]=useState('');const options=countries.filter(c=>`${c.name} ${c.iso3} ${c.iso2}`.toLowerCase().includes(q.toLowerCase()));
 return <div className="atlas-country-search"><label>{label}<input aria-label={'Search '+label.toLowerCase()} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name or country code…"/></label><select aria-label={label} value={selected||''} onChange={e=>{if(e.target.value){onSelect(e.target.value);setQ('');}}}><option value="">Choose a country</option>{options.map(c=><option key={c.iso3} value={c.iso3}>{c.name} · {c.iso3}</option>)}</select></div>;
}
function Explain({meta,atlas}:{meta:IndicatorMeta;atlas:Atlas}){const source=meta.source_id?atlas.sources?.[meta.source_id]:undefined;return <details className="panel atlas-explain"><summary><Info size={17}/> Explain this indicator <ChevronDown size={16}/></summary><div className="atlas-definition"><h3>{meta.label}</h3><dl><div><dt>Unit</dt><dd>{meta.unit}</dd></div><div><dt>Frequency</dt><dd>{meta.frequency}</dd></div><div><dt>Data status</dt><dd>{meta.status}</dd></div><div><dt>Global coverage</dt><dd>{meta.coverage} of {atlas.countries.length} profiles</dd></div></dl><p>{meta.methodology||'See the source definition.'}</p><div className="callout"><strong>Using this with SWITCH</strong><p>{meta.switch_relevance}</p></div><p><a href={meta.source_url} target="_blank" rel="noreferrer">{meta.source} <ArrowUpRight size={14}/></a></p><p className="muted">Published/updated: {meta.publication_date||'Not supplied'} · retrieved: {meta.retrieved_at?.slice(0,10)}. {source?.license}</p><p className="muted">{meta.missing_reason}</p></div></details>;}
function Mix({title,mix,unit}:{title:string;mix:ReturnType<typeof commonMix>;unit:string}){return <div className="chart-panel"><h3>{title}</h3><p className="muted">{mix.period?`${mix.period} · ${unit} · same year for reported categories${mix.missing?` · ${mix.missing} unreported categories omitted`:``}`:'No common year with every category reported.'}</p><div className="chart">{mix.rows.length>0?<ResponsiveContainer width="100%" height="100%"><BarChart data={mix.rows.filter(r=>r.value!==0)} layout="vertical" margin={{left:0,right:15}}><CartesianGrid horizontal={false} stroke="#273d4e"/><XAxis type="number" stroke="#97afbe" tickFormatter={v=>compact(v)}/><YAxis type="category" dataKey="name" width={125} stroke="#97afbe" fontSize={12}/><Tooltip contentStyle={tooltip} formatter={v=>[number(Number(v),3),unit]}/><Bar dataKey="value" fill="#67d6c4" isAnimationActive={false} radius={[0,4,4,0]}/></BarChart></ResponsiveContainer>:<p className="atlas-empty">Category coverage is incomplete. Explore individual technology indicators below.</p>}</div></div>;}

export default function CountryAtlas({atlas,selected,onSelect}:{atlas:Atlas|null;selected:string;onSelect:(s:string)=>void}){
 const [view,setView]=useState('explore'),[category,setCategory]=useState('generation'),[metric,setMetric]=useState('share_renewables'),[query,setQuery]=useState(''),[period,setPeriod]=useState('latest'),[normalization,setNormalization]=useState('absolute'),[compare,setCompare]=useState(['KEN','SAU','ARE','USA']),[hist,setHist]=useState<Histories>({}),[historyErrors,setHistoryErrors]=useState<string[]>([]),[pending,setPending]=useState(0),[retry,setRetry]=useState(0),[assetStore,setAssetStore]=useState<Record<string,PowerAsset[]>>({}),[assetLoading,setAssetLoading]=useState(false),[assetError,setAssetError]=useState(''),[assetDataset,setAssetDataset]=useState('gem'),[assetType,setAssetType]=useState('all'),[assetStatus,setAssetStatus]=useState('operating'),[assetQuery,setAssetQuery]=useState(''),[assetPage,setAssetPage]=useState(0);
 const loaded=useRef(new Set<string>()),loading=useRef(new Set<string>()),assetsLoaded=useRef(new Set<string>()),chartRef=useRef<HTMLDivElement>(null);const reduce=useReducedMotion();
 const country=atlas?.countries.find(c=>c.iso3===selected);const meta=atlas?.metadata[metric];
 const compareKey=compare.join(',');
 useEffect(()=>{
  if(!atlas)return;const isos=period==='latest'&&normalization==='absolute'?[selected,...compare]:atlas.countries.map(c=>c.iso3);const paths=[...new Set(isos.map(iso=>atlas.history_files?.[iso[0]]).filter(Boolean))] as string[];let active=true;
  for(const path of paths){if(loaded.current.has(path)||loading.current.has(path))continue;loading.current.add(path);setPending(v=>v+1);
   fetchAtlasJSON<Histories>(path).then((data:Histories)=>{loaded.current.add(path);setHist(h=>({...h,...data}));setHistoryErrors(x=>x.filter(v=>v!==path));}).catch(()=>{setHistoryErrors(x=>[...new Set([...x,path])]);}).finally(()=>{loading.current.delete(path);setPending(v=>Math.max(0,v-1));});
  }
  return()=>{active=false;};
 },[atlas,selected,compareKey,period,normalization,retry]);
 useEffect(()=>{if(!atlas||view!=='infrastructure')return;const path=atlas.asset_files?.[selected[0]];if(!path)return;if(assetsLoaded.current.has(path)){setAssetLoading(false);return;}let active=true;setAssetLoading(true);setAssetError('');fetchAtlasJSON<Record<string,PowerAsset[]>>(path).then((d:Record<string,PowerAsset[]>)=>{assetsLoaded.current.add(path);setAssetStore(v=>({...v,...d}));}).catch(e=>{if(active)setAssetError(e.message);}).finally(()=>{setAssetLoading(false);});return()=>{active=false;};},[atlas,selected,view,retry]);
 useEffect(()=>{setAssetPage(0);},[selected,assetDataset,assetType,assetStatus,assetQuery]);
 const comparison=useMemo(()=>compare.map(iso=>atlas?.countries.find(c=>c.iso3===iso)).filter(Boolean) as Country[],[atlas,compare]);
 const metrics=useMemo(()=>Object.entries(atlas?.metadata||{}).filter(([k,m])=>(query?`${m.label} ${m.unit} ${k} ${m.source}`.toLowerCase().includes(query.toLowerCase()):m.category===category)),[atlas,query,category]);
 const histReady=!!hist[selected];
 const values=useMemo(()=>atlas&&meta?transformedSeries(seriesFor(atlas,hist,selected,metric),meta,seriesFor(atlas,hist,selected,'population'),normalization):[],[atlas,hist,selected,metric,meta,normalization]);
 const bars=useMemo(()=>atlas?comparison.map(c=>({name:c.name,iso:c.iso3,obs:comparisonObservation(atlas,hist,c,metric,period,normalization)})).map(x=>({...x,value:typeof x.obs?.value==='number'?x.obs.value:null,period:x.obs?periodOf(x.obs):'No data'})):[],[atlas,comparison,hist,metric,period,normalization]);
 const trends=useMemo(()=>{if(!atlas||!meta)return [];const out:Record<string,Record<string,string|number|null>>={};if(meta.frequency==='annual'){for(let y=2010;y<=atlas.latest_completed_year;y++)out[String(y)]={period:String(y),...Object.fromEntries(comparison.map(c=>[c.iso3,null]))};}for(const c of comparison){for(const o of transformedSeries(seriesFor(atlas,hist,c.iso3,metric),meta,seriesFor(atlas,hist,c.iso3,'population'),normalization)){const p=periodOf(o);out[p]||={period:p};out[p][c.iso3]=typeof o.value==='number'?o.value:null;}}return Object.values(out).sort((a,b)=>String(a.period).localeCompare(String(b.period)));},[atlas,hist,comparison,metric,meta,normalization]);
 const mappedCountries=useMemo(()=>atlas?atlas.countries.map(c=>({...c,indicators:{...c.indicators,[metric]:{...(comparisonObservation(atlas,hist,c,metric,period,normalization)||{value:null,year:null}),history:[]}}})):[],[atlas,hist,metric,period,normalization]);
 const allAssets=assetStore[selected]||[];const assets=useMemo(()=>allAssets.filter(a=>(a.source_id||'gem')===assetDataset),[allAssets,assetDataset]);const assetTypes=[...new Set(assets.map(a=>a.type))].sort();const assetStatuses=[...new Set(assets.map(a=>a.status))].sort();
 const filteredAssets=useMemo(()=>assets.filter(a=>(assetType==='all'||a.type===assetType)&&(assetStatus==='all'||a.status===assetStatus)&&`${a.name} ${a.phase} ${a.technology} ${a.fuel}`.toLowerCase().includes(assetQuery.toLowerCase())),[assets,assetType,assetStatus,assetQuery]);
 if(!atlas||!meta)return <div className="empty"><LoaderCircle className="spin"/><h2>Loading the energy atlas</h2></div>;
 const current=country?comparisonObservation(atlas,hist,country,metric,period,normalization):undefined,unit=displayUnit(meta,normalization),isNumber=meta.value_type!=='text',categories=atlas.categories||[];
 const changeMetric=(key:string)=>{setMetric(key);setPeriod('latest');setNormalization('absolute');setCategory(atlas.metadata[key].category||'context');};
 const changeCategory=(id:string)=>{setCategory(id);setQuery('');const candidates=Object.entries(atlas.metadata).filter(([,m])=>m.category===id);changeMetric((candidates.find(([,m])=>(m.coverage||0)>0)||candidates[0])?.[0]||metric);setView('explore');};
 function exportChart(){const svgs=chartRef.current?.querySelectorAll<SVGSVGElement>('svg.recharts-surface');if(!svgs?.length)return;const widths=[...svgs].map(s=>s.viewBox.baseVal.width||s.getBoundingClientRect().width);let y=85;const parts=[...svgs].map(s=>{const h=s.viewBox.baseVal.height||s.getBoundingClientRect().height;const clone=s.cloneNode(true) as SVGElement;clone.setAttribute('y',String(y));y+=h+25;return new XMLSerializer().serializeToString(clone);});const escape=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');const caption=`${meta!.label} · ${unit} · ${period} · ${normalization}`;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${Math.max(850,...widths)}" height="${y+90}"><rect width="100%" height="100%" fill="#101f2e"/><g fill="#edf7fc" font-family="sans-serif"><text x="20" y="30" font-size="18">${escape(caption)}</text><text x="20" y="58" font-size="12">${escape(comparison.map(c=>c.name).join(' · '))}</text></g>${parts.join('')}<text x="20" y="${y+20}" fill="#bdcfda" font-family="sans-serif" font-size="11">${escape(meta!.source+' · '+meta!.source_url)}</text><text x="20" y="${y+43}" fill="#bdcfda" font-family="sans-serif" font-size="11">Retrieved ${escape(meta!.retrieved_at.slice(0,10))}; observations retain individual periods. Missing values are gaps.</text></svg>`;saveFile(svg,`switch-atlas-${metric}.svg`,'image/svg+xml');}
 return <>
  <div className="page-heading atlas-page-heading"><div><div className="eyebrow">COUNTRIES · ELECTRICITY · ENERGY SYSTEMS</div><h1>Global energy atlas</h1><p>{atlas.countries.length} country and territory profiles · {Object.values(atlas.metadata).filter(m=>(m.coverage||0)>0).length} indicators with observations · snapshot {atlas.retrieved_at.slice(0,10)}</p></div><span className="subtle-badge"><Database size={16}/> Local data · available offline</span></div>
  <div className="atlas-main-toolbar"><CountrySearch countries={atlas.countries} selected={selected} onSelect={onSelect}/><div className="atlas-view-tabs" role="group" aria-label="Atlas view">{[['overview','Country overview'],['explore','Explore & compare'],['infrastructure','Infrastructure'],['sources','Data coverage']].map(([id,label])=><button className={view===id?'active':''} aria-pressed={view===id} key={id} onClick={()=>setView(id)}>{label}</button>)}</div></div>
  <div className="atlas-categories" role="group" aria-label="Energy sections">{categories.map(cat=><button key={cat.id} aria-pressed={category===cat.id} className={category===cat.id?'active':''} onClick={()=>changeCategory(cat.id)}><span>{cat.label}</span><small>{country?.coverage?.[cat.id]||0} available</small></button>)}</div>
  {historyErrors.length>0&&<div className="banner">Some history files could not load. <button className="text-button" onClick={()=>setRetry(v=>v+1)}>Retry</button></div>}
  {pending>0&&<p role="status" className="atlas-loading"><LoaderCircle className="spin" size={14}/> Loading historical observations…</p>}
  <AnimatePresence mode="wait"><motion.div key={view} initial={{opacity:0,y:reduce?0:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:reduce?0:0.18}}>
  {view==='overview'&&<>
   <div className="section-heading"><h2>{country?.name||selected} · energy overview</h2><button className="button secondary" onClick={()=>{if(country)saveFile(observationCSV(atlas,Object.keys(atlas.metadata).map(key=>({country,key,obs:country.indicators[key]}))),`switch-atlas-${selected}-profile.csv`);}}><ArrowDownToLine size={15}/> Export profile</button></div>
   <div className="overview-metrics">{['generation_total','demand_total','share_renewables','power_intensity'].map(key=>{const o=country?.indicators[key];return <button className="stat atlas-stat" key={key} onClick={()=>{changeMetric(key);setView('explore');}}><span>{atlas.metadata[key]?.label}</span><strong>{compact(o?.value)}</strong><small>{atlas.metadata[key]?.unit} · {o?.value!=null?periodOf(o):'No observation'}</small></button>;})}</div>
   <div className="chart-grid"><Mix title="Electricity generation mix" mix={commonMix(atlas,hist,selected,generationKeys)} unit="TWh"/><Mix title="Selected grid-connected capacity" mix={commonMix(atlas,hist,selected,capacityKeys,false)} unit="GW"/></div>
   <div className="chart-grid">{['demand_total','power_emissions'].map(key=><div className="chart-panel" key={key}><h3>{atlas.metadata[key].label}</h3><p className="muted">{atlas.metadata[key].unit} · {atlas.metadata[key].source}</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={seriesFor(atlas,hist,selected,key)}><CartesianGrid stroke="#273d4e"/><XAxis dataKey="year" stroke="#94adbe"/><YAxis stroke="#94adbe" tickFormatter={v=>compact(v)}/><Tooltip contentStyle={tooltip}/><Line dataKey="value" stroke="#67d6c4" dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div></div>)}</div>
   <p className="data-note">Generation: Ember; capacity: IRENA. Capacity chart shows selected technologies, not a national total. Power emissions are lifecycle CO₂e estimates. Country context does not automatically change SWITCH inputs.</p>
  </>}
  {view==='explore'&&<>
   <div className="atlas-explorer-controls"><label><span><Search size={14}/> Search every energy indicator</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Solar, imports, residential, emissions…"/></label><label>Indicator<select value={metrics.some(([k])=>k===metric)?metric:''} onChange={e=>changeMetric(e.target.value)}><option value="" disabled>{metrics.length?'Select indicator':'No matching indicators'}</option>{metrics.map(([key,m])=><option value={key} key={key}>{m.label}{m.coverage===0?' · no connected observations':''}</option>)}</select></label><label>Observation period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="latest">Latest available (periods may differ)</option>{[...(meta.periods||[])].reverse().map(p=><option key={p} value={p}>{p} · same period</option>)}</select></label><label>Display<select value={normalization} onChange={e=>setNormalization(e.target.value)}><option value="absolute">As reported · {meta.unit}</option>{meta.per_capita&&meta.frequency==='annual'&&<option value="per_capita">Per person · same-year population</option>}{isNumber&&meta.frequency==='annual'&&!meta.unit.startsWith('%')&&<option value="growth">Year-on-year change (%)</option>}</select></label></div>
   <div className="world-layout atlas-world">
    <Globe country={country} countries={mappedCountries} onSelect={onSelect} layer={isNumber&&meta.map_eligible!==false?metric:'model'} indicatorMeta={meta} unit={unit} period={period} normalization={normalization} loading={pending>0&&period!=='latest'}/>
    <AtlasCountryPanel key={selected} atlas={atlas} country={country} histories={hist} metric={metric} meta={meta} current={current} unit={unit} period={period} normalization={normalization} values={values} historyLoading={!histReady&&pending>0} onMetric={changeMetric} onOverview={()=>setView('overview')} onCompare={()=>setCompare(v=>v.includes(selected)||v.length>=6?v:[...v,selected])} inComparison={compare.includes(selected)} comparisonFull={compare.length>=6}/>
   </div>
   <Explain meta={meta} atlas={atlas}/>
   <div className="section-heading"><h2>Compare countries</h2><div className="button-row"><button className="button secondary small" onClick={()=>saveFile(observationCSV(atlas,comparison.map(country=>({country,key:metric,obs:comparisonObservation(atlas,hist,country,metric,period,normalization),unit}))),`switch-atlas-${metric}-comparison.csv`)}><ArrowDownToLine size={14}/> CSV</button>{isNumber&&<button className="button secondary small" onClick={exportChart}><ArrowDownToLine size={14}/> Charts SVG</button>}</div></div>
   <div className="country-chips">{comparison.map(c=><span key={c.iso3}>{c.name}<button aria-label={'Remove '+c.name} onClick={()=>setCompare(v=>v.filter(x=>x!==c.iso3))}><X size={14}/></button></span>)}</div>{compare.length<6&&<CountrySearch label="Add comparison country" countries={atlas.countries.filter(c=>!compare.includes(c.iso3))} onSelect={iso=>setCompare(v=>[...v,iso])}/>}
   <p className="data-note">{period==='latest'?'Latest mode can compare different periods; each is listed below. Select a specific period for a matched comparison.':'All countries use the selected period; missing observations stay empty.'} {normalization==='per_capita'&&'Population must match the observation year.'} Percentage indicators keep their original denominator.</p>
   {isNumber&&<div ref={chartRef} className="chart-grid atlas-comparison-charts"><div className="chart-panel"><h3>{meta.label}</h3><p>{unit} · {period}</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={bars}><CartesianGrid vertical={false} stroke="#273d4e"/><XAxis dataKey="iso" stroke="#94adbe"/><YAxis stroke="#94adbe" tickFormatter={v=>compact(v)}/><Tooltip contentStyle={tooltip} formatter={v=>[number(Number(v),3),unit]} labelFormatter={(_,p)=>`${p[0]?.payload?.name||''} · ${p[0]?.payload?.period||''}`}/><Bar dataKey="value" fill="#67d6c4" isAnimationActive={false} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="chart-panel"><h3>Historical comparison</h3><p>{unit} · {meta.frequency==='climatology'?'resource study reference':meta.frequency}</p><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trends}><CartesianGrid stroke="#273d4e"/><XAxis dataKey="period" stroke="#94adbe" minTickGap={38}/><YAxis stroke="#94adbe" tickFormatter={v=>compact(v)}/><Tooltip contentStyle={tooltip} formatter={v=>[number(Number(v),3),unit]}/><Legend/>{comparison.map((c,i)=><Line key={c.iso3} dataKey={c.iso3} name={c.name} stroke={colors[i]} dot={trends.length<3} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div></div></div>}
   <div className="panel table-scroll"><table><thead><tr><th>Country</th><th>{meta.label}</th><th>Period</th><th>Unit</th></tr></thead><tbody>{bars.map(r=><tr key={r.iso}><td>{r.name}</td><td>{valueText(r.obs)}</td><td>{r.period}</td><td>{unit}</td></tr>)}</tbody></table></div>
   <details className="panel"><summary>All {query?'matching':categories.find(c=>c.id===category)?.label.toLowerCase()} indicators · {metrics.length}</summary><div className="table-scroll"><table><thead><tr><th>Indicator / unit</th>{comparison.map(c=><th key={c.iso3}>{c.name}</th>)}</tr></thead><tbody>{metrics.map(([key,m])=><tr key={key}><td><button className="text-button" onClick={()=>changeMetric(key)}>{m.label}</button><small className="block muted">{m.unit} · {m.frequency}</small></td>{comparison.map(c=>{const o=period==='latest'?c.indicators[key]:seriesFor(atlas,hist,c.iso3,key).find(o=>periodOf(o)===period);return <td key={c.iso3}>{valueText(o)}<small className="block muted">{o?.value!=null?periodOf(o):'No matching period'}</small></td>;})}</tr>)}</tbody></table></div></details>
   <details className="panel"><summary>{country?.name} · observations and download</summary><button className="button secondary small" disabled={!country||!histReady} onClick={()=>{if(country)saveFile(observationCSV(atlas,values.map(obs=>({country,key:metric,obs,unit}))),`switch-atlas-${selected}-${metric}-history.csv`);}}>Export historical series</button><div className="table-scroll atlas-history-table"><table><thead><tr><th>Period</th><th>Value</th><th>Unit</th><th>Source flag / note</th></tr></thead><tbody>{values.slice().reverse().map(o=><tr key={periodOf(o)}><td>{periodOf(o)}</td><td>{valueText(o)}</td><td>{unit}</td><td>{o.flag||o.note||'—'}</td></tr>)}</tbody></table></div></details>
   {category==='prices'&&atlas.benchmarks&&<div className="panel"><h2>Global technology cost references · {atlas.benchmarks.year}</h2><p>{atlas.benchmarks.scope}</p><div className="table-scroll"><table><thead><tr><th>Technology</th><th>LCOE (2025 USD/MWh)</th><th>Installed cost (2025 USD/kW)</th><th>Capacity factor</th></tr></thead><tbody>{atlas.benchmarks.technologies.map(b=><tr key={b.technology}><td>{b.technology}</td><td>{b.lcoe_usd_mwh}</td><td>{number(b.capex_usd_kw)}</td><td>{b.capacity_factor_pct}%</td></tr>)}</tbody></table></div><p>Four-hour utility-scale battery benchmark: {atlas.benchmarks.battery.installed_usd_kwh} USD/kWh installed. {atlas.benchmarks.battery.scope}</p><a href={atlas.sources?.[atlas.benchmarks.source_id]?.source_url} target="_blank" rel="noreferrer">IRENA report · Figure S1 <ArrowUpRight size={14}/></a></div>}
   {category==='storage'&&<div className="panel"><h2>Battery project records</h2><p>The historical DOE/NTESS inventory provides reported MW, MWh and paired-rating durations. It is dated January 2022 and must not be treated as a current national total.</p><button className="button secondary" onClick={()=>{setAssetDataset('doe_storage');setAssetType('all');setView('infrastructure');}}>Explore historical storage projects</button></div>}
   {category==='resources'&&<div className="panel"><h2>Explore the resource at a site</h2><p>Country averages screen potential; site weather and terrain are needed for a capacity-factor time series.</p><div className="button-row"><a className="button secondary" href="https://globalsolaratlas.info/" target="_blank" rel="noreferrer">Global Solar Atlas <ArrowUpRight size={14}/></a><a className="button secondary" href="https://globalwindatlas.info/" target="_blank" rel="noreferrer">Global Wind Atlas <ArrowUpRight size={14}/></a></div></div>}
  </>}
  {view==='infrastructure'&&<>
   <div className="section-heading"><h2>{country?.name} · power projects</h2><span className="subtle-badge">{assetDataset==='gem'?'GEM · February 2026':'DOE / NTESS · January 2022 (historical)'}</span></div><p>Explore plant units and project phases. Capacity is an inventory subtotal, with technology-specific coverage thresholds; it is not the national total. Locations may be approximate. Choose the historical DOE inventory to inspect battery and chemical storage. Interconnector routes are not included. The DOE snapshot is from 2022 and is not a current national storage total.</p>
   <div className="atlas-explorer-controls"><label>Inventory<select value={assetDataset} onChange={e=>{setAssetDataset(e.target.value);setAssetType('all');}}><option value="gem">Power plants · GEM February 2026</option><option value="doe_storage">Battery / chemical storage · DOE January 2022</option></select></label><label>Technology<select value={assetType} onChange={e=>setAssetType(e.target.value)}><option value="all">All technologies</option>{assetTypes.map(t=><option key={t}>{t}</option>)}</select></label><label>Project status<select value={assetStatus} onChange={e=>setAssetStatus(e.target.value)}><option value="all">All statuses</option>{[...new Set(['operating',...assetStatuses])].map(s=><option key={s}>{s}</option>)}</select></label><label>Find a plant<input value={assetQuery} onChange={e=>setAssetQuery(e.target.value)} placeholder="Project, fuel or technology"/></label><button className="button secondary" disabled={assetLoading} onClick={()=>saveFile(makeCSV([['country','GEM unit ID','project','phase','type','technology','fuel','allocated capacity MW','energy MWh','duration hours','status','start year','retired year','latitude','longitude','location accuracy','shared facility','source','inventory vintage'],...filteredAssets.map(a=>[country?.name,a.unit_id,a.name,a.phase,a.type,a.technology,a.fuel,a.capacity_mw,a.energy_mwh,a.duration_hours,a.status,a.start_year,a.retired_year,a.lat,a.lon,a.location_accuracy,a.shared,a.url,a.vintage||'2026-02'])]),`switch-atlas-${selected}-projects.csv`)}><ArrowDownToLine size={15}/> Export projects</button></div>
   {assetLoading?<p role="status"><LoaderCircle className="spin" size={16}/> Loading country inventory…</p>:assetError?<p role="alert">{assetError} <button onClick={()=>setRetry(v=>v+1)}>Retry</button></p>:<><Globe key={assetDataset} country={country} countries={atlas.countries} onSelect={onSelect} layer="model" assets={filteredAssets} assetAttribution={assetDataset==='gem'?'Global Energy Monitor · CC BY 4.0 · February 2026':'DOE / NTESS · January 2022 · historical inventory'} legendNote={`${filteredAssets.length} matching unit/phase records · ${assetDataset==='gem'?'February 2026':'January 2022 historical inventory'} · approximate locations possible`}/><p className="data-note">{number(filteredAssets.length,0)} matching records · {number(filteredAssets.filter(a=>a.capacity_mw!=null).reduce((s,a)=>s+(a.capacity_mw||0),0),1)} MW reported capacity. Missing capacities are excluded from this subtotal.</p><div className="panel table-scroll"><table><thead><tr><th>Project / phase</th><th>Technology</th><th>MW</th>{assetDataset==='doe_storage'&&<><th>MWh</th><th>Hours</th></>}<th>Status</th><th>Start / retired</th><th>Location</th></tr></thead><tbody>{filteredAssets.slice(assetPage*40,(assetPage+1)*40).map(a=><tr key={a.id}><td>{a.url&&/^https:\/\//.test(a.url)?<a href={a.url} target="_blank" rel="noreferrer">{a.name} <ArrowUpRight size={12}/></a>:a.name}<small className="block muted">{a.phase||a.unit_id}{a.shared?' · shared facility allocation':''}</small></td><td>{a.type}<small className="block muted">{a.technology||a.fuel}</small></td><td>{number(a.capacity_mw,2)}</td>{assetDataset==='doe_storage'&&<><td>{number(a.energy_mwh,2)}</td><td>{number(a.duration_hours,2)}</td></>}<td>{a.status}</td><td>{a.start_year||'—'} / {a.retired_year||'—'}</td><td>{a.lat==null||a.lon==null?'Unreported':`${number(a.lat,3)}, ${number(a.lon,3)}`}<small className="block muted">{a.location_accuracy}</small></td></tr>)}</tbody></table></div>{!filteredAssets.length&&<p>No matching records in this inventory. This does not establish that the country has no plants.</p>}<div className="button-row"><button className="button secondary small" disabled={assetPage===0} onClick={()=>setAssetPage(v=>v-1)}>Previous</button><span>Page {assetPage+1} of {Math.max(1,Math.ceil(filteredAssets.length/40))}</span><button className="button secondary small" disabled={(assetPage+1)*40>=filteredAssets.length} onClick={()=>setAssetPage(v=>v+1)}>Next</button></div></>}
  </>}
  {view==='sources'&&<>
   <div className="section-heading"><h2>What is available for {country?.name||selected}?</h2><button className="button secondary" onClick={()=>saveFile(makeCSV([['section','indicator','unit','frequency','countries with observations','country value','country period','source','source_url','missing reason'],...Object.entries(atlas.metadata).map(([key,m])=>[m.category,m.label,m.unit,m.frequency,m.coverage,country?.indicators[key]?.value,country?.indicators[key]?.period,m.source,m.source_url,country?.indicators[key]?.value==null?m.missing_reason:''])]),`switch-atlas-${selected}-coverage.csv`)}><ArrowDownToLine size={15}/> Export coverage</button></div>
   <p>Every profile has the same indicator schema. “No data” preserves a gap; zero is shown only when the source reports zero. Latest annual values may predate 2025. Monthly 2026 observations, snapshot policies and long-term resource studies keep their own periods.</p>
   <div className="atlas-coverage-grid">{categories.map(cat=>{const ms=Object.entries(atlas.metadata).filter(([,m])=>m.category===cat.id);return <details className="panel" key={cat.id}><summary><span>{cat.label}</span><strong>{country?.coverage?.[cat.id]||0} / {ms.length}</strong></summary><p>{cat.description}</p>{ms.map(([key,m])=><div className="atlas-coverage-row" key={key}><button className="text-button" onClick={()=>{changeMetric(key);setView('explore');}}>{m.label}</button><small>{country?.indicators[key]?.value!=null?<><Check size={12}/> {periodOf(country.indicators[key])}</>:m.missing_reason}</small></div>)}</details>;})}</div>
   <h2>Source register</h2>{Object.entries(atlas.sources||{}).filter(([key])=>key!=='coverage_notes').map(([key,s])=><details className="panel source-details" key={key}><summary>{s.name}<ChevronDown size={15}/></summary><p><a href={s.source_url} target="_blank" rel="noreferrer">Source publication <ArrowUpRight size={14}/></a></p><p>Retrieved {s.retrieved_at.slice(0,10)} · published/updated {s.publication_date||'See indicator metadata'}. {s.license}</p>{s.note&&<p>{s.note}</p>}{s.sha256&&<p className="atlas-hash">Source file SHA-256: {s.sha256}</p>}</details>)}
   <p className="data-note">Natural Earth boundaries, public domain. Some small territories require the country picker. National contextual data, country-specific SWITCH inputs and model outputs remain separately identified.</p>
  </>}
  </motion.div></AnimatePresence>
 </>;
}
