'use client';
import {useState} from 'react';
import katex from 'katex';
import {ArrowUpRight,BookOpen,Lightbulb} from 'lucide-react';

function MathBlock({tex}:{tex:string}){return <div className="equation" dangerouslySetInnerHTML={{__html:katex.renderToString(tex,{displayMode:true,throwOnError:false,output:'htmlAndMathml'})}}/>;}
const variables=[
 ['p','Index','Investment period','year label','2020 or 2030 in the tiny tutorial','periods.csv'],
 ['t','Index','Sampled operating timepoint','index','A representative hour or block; not necessarily every hour','timepoints.csv'],
 ['g','Index','Generation project','project ID','A technology at a specific location','gen_info.csv'],
 ['z','Index','Load zone','zone ID','A network node; county zones in Kenya','load_zones.csv'],
 ['zone_demand_mw[z,t]','Input parameter','Power demanded','MW','Edit demand data or the scenario multiplier','loads.csv'],
 ['BuildGen[g,p]','Decision variable','New generation capacity','MW','The solver chooses investment; positive minimum builds can introduce binaries','generators/core/build.py'],
 ['DispatchGen[g,t]','Decision variable','Generator power output','MW','Changes by timepoint within the installed capacity limit','generators/core/dispatch.py'],
 ['GenCapacity[g,p]','Expression','Installed surviving capacity','MW','Existing assets and previous builds that have not retired','generators/core/build.py'],
 ['gen_max_capacity_factor[g,t]','Input parameter','Variable resource availability','fraction','Availability limit, not necessarily realized capacity factor','variable_capacity_factors.csv'],
 ['tp_weight_in_year[t]','Derived parameter','Annual representation of timepoint','hours/year','Multiply power by this weight to calculate typical-year energy','timescales.py'],
 ['discount_rate','Input parameter','Discount future system costs','fraction/year','Separate from the interest rate used for financing','financials.csv'],
 ['interest_rate','Input parameter','Financing interest rate','fraction/year','Used with asset life in capital recovery','financials.csv'],
 ['SystemCost','Objective','Discounted total system cost','base-year currency','Compare only compatible horizons, currency and assumptions','financials.py'],
 ['BuildStorageEnergy[g,p]','Decision variable','New storage energy capacity','MWh','Different from charging/discharging power in MW; active module required','generators/extensions/storage.py'],
 ['πₛ','Input parameter','Probability of uncertain scenario','fraction','Probabilities sum to one; different from hour weights','Teaching lab'],
 ['x','Decision variable','Investment before uncertainty resolves','MW','One shared investment decision across all scenarios','Teaching lab'],
 ['yₛ','Decision variable','Operation after scenario is known','MW','Recourse can differ across scenarios','Teaching lab'],
 ['α, λ','Input parameters','CVaR confidence and risk weight','fraction','α defines the tail; λ controls expected-cost/CVaR blending','Teaching lab'],
];
export default function Learning(){const[lesson,setLesson]=useState(0);return <div className="learning"><div className="page-heading"><div><div className="eyebrow">LEARN THE MODEL</div><h1>From intuition to equations</h1><p>Start with SWITCH’s core logic, then follow what changes in Kenya.</p></div><BookOpen className="heading-icon"/></div><div className="segmented">{['Core model','Variables & units','Uncertainty','Kenya extension'].map((s,i)=><button key={s} aria-pressed={lesson===i} className={lesson===i?'active':''} onClick={()=>setLesson(i)}>{s}</button>)}</div>
 {lesson===0&&<div className="lesson-grid"><article className="panel prose"><span className="eyebrow">01 / DECIDE WHAT TO BUILD</span><h2>A feasible electricity system at minimum modeled cost</h2><p>SWITCH chooses generation, storage and network investments alongside operation. Inputs define the available technologies, demand, costs and policy rules. The solver searches for decisions that satisfy every active constraint.</p><MathBlock tex={String.raw`\min\; \sum_p DF_p\left[C_p^{\mathrm{annual}}+\sum_{t\in p}w_t C_t^{\mathrm{hourly}}\right]`}/><p>This is a schematic objective. SWITCH’s financial factors account for the years represented by each investment period. Its active modules register annual and timepoint costs.</p><h3>Power must balance at every modeled zone and timepoint</h3><MathBlock tex={String.raw`\mathrm{generation}+\mathrm{imports}+\mathrm{discharge}=\mathrm{demand}+\mathrm{exports}+\mathrm{charge}+\mathrm{losses}`}/><p>Losses appear in the appropriate transmission or local-distribution equations. They must not be counted twice. The exact balance depends on the selected modules.</p><h3>Generation is limited by installed capacity</h3><MathBlock tex={String.raw`0\leq \mathrm{DispatchGen}_{g,t}\leq \mathrm{GenCapacity}_{g,p(t)}\; a_{g,t}`}/><p>The availability factor includes the relevant resource and outage assumptions. Renewable output may be curtailed even when resources are available.</p></article><aside className="panel prose"><Lightbulb className="accent"/><h2>Three distinctions that matter</h2><h3>MW versus MWh</h3><p>MW is power. MWh is energy. A 10 MW plant operating for 3 hours supplies 30 MWh.</p><MathBlock tex={String.raw`E_g=\sum_t P_{g,t}\,w_t`}/><h3>Inputs versus decisions</h3><p>You edit a fuel price or a capacity limit. The solver chooses dispatch and new capacity. Changing a solver decision requires an explicit bound or fixed-value constraint.</p><h3>Annualized versus overnight cost</h3><MathBlock tex={String.raw`\mathrm{CRF}(r,n)=\frac{r(1+r)^n}{(1+r)^n-1}`}/><p>For a zero interest rate, CRF = 1/n. Annualized capital cost is overnight cost times CRF. Discounting then expresses modeled annual costs in a common base year.</p><div className="callout">A least-cost solution is conditional on the inputs and model boundary. It is not a forecast or a complete measure of social welfare.</div></aside></div>}
 {lesson===1&&<div className="panel"><div className="panel-heading"><h2>Variable and parameter reference</h2><span className="muted">Module-dependent · pinned SWITCH 2.0.9</span></div><div className="table-scroll"><table><thead><tr>{['Symbol / object','Type','Meaning','Units','Interpretation','Source'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{variables.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{i===0?<code>{v}</code>:v}</td>)}</tr>)}</tbody></table></div></div>}
 {lesson===2&&<div className="lesson-grid"><article className="panel prose"><span className="eyebrow">03 / DECIDE BEFORE YOU KNOW</span><h2>Stochastic optimization</h2><p>Choose one investment plan before demand is known. When demand is revealed, dispatch can adapt. Scenario probabilities enter the optimization itself.</p><MathBlock tex={String.raw`\min_{x,\{y_s\}} c^T x+\sum_s \pi_s q_s^T y_s\quad\text{with}\quad\sum_s\pi_s=1`}/><p>Every scenario uses the same first-stage investment x. If each scenario independently chooses its investment, that is a perfect-information benchmark, not the implementable stochastic plan.</p><MathBlock tex={String.raw`x_s=x_{s'}\quad \forall s,s'\qquad\text{(non-anticipativity)}`}/><h3>Expected cost and tail risk</h3><MathBlock tex={String.raw`\mathrm{CVaR}_{\alpha}(C)=\min_{\eta}\left[\eta+\frac{\sum_s\pi_s\max(C_s-\eta,0)}{1-\alpha}\right]`}/><p>The lab minimizes (1 − λ) × expected cost + λ × CVaR. At λ = 0 it is risk-neutral. The risk-neutral benchmark is solved separately when calculating VSS and EVPI.</p><MathBlock tex={String.raw`\mathrm{VSS}=\mathrm{EEV}-\mathrm{RP}\qquad\mathrm{EVPI}=\mathrm{RP}-\mathrm{WS}`}/><p>RP: optimal risk-neutral stochastic cost. EEV: expected cost when the deterministic mean-demand investment is fixed and operation adapts. WS: probability-weighted optimum with perfect information.</p></article><aside className="panel prose"><h2>Which experiment are you doing?</h2><h3>Sensitivity analysis</h3><p>Change an assumption and solve again. Separate investment decisions show how the optimum responds; they are not a single uncertainty-aware plan.</p><h3>Monte Carlo simulation</h3><p>Sample uncertain inputs and evaluate outcomes. Sampling can generate scenarios for optimization, but sampling alone does not impose shared investments.</p><h3>Two-stage teaching lab</h3><p>Three demand outcomes have probabilities 25%, 50% and 25%. Firm and solar capacity are shared; dispatch and unmet demand adapt. Costs and resource values are illustrative.</p><div className="callout">The learning lab is a separate small Pyomo model. It does not add stochastic behavior to the Kenya model. A SWITCH extensive-form adapter needs its own investment mapping and parity tests.</div></aside></div>}
 {lesson===3&&<article className="panel prose wide-prose"><span className="eyebrow">04 / FROM FRAMEWORK TO COUNTRY</span><h2>What Xi Xi’s Kenya model adds</h2><p>Country inputs instantiate the generic SWITCH equations: 47 county zones, 133 corridors, 24 annual investment periods from 2027 to 2050, and 1,152 sampled timepoints. The base configuration adds storage, planning reserves and a project-specific generation-build-limits module.</p><p>Hydrogen configurations additionally load an electrolyzer module. They are separate variants; selecting the base Kenya adapter does not activate hydrogen automatically.</p><ol><li><strong>Reuse the framework.</strong> Time indexing, financing, generation build/dispatch and transport transmission come from core SWITCH modules.</li><li><strong>Describe Kenya with data.</strong> Replace zones, load profiles, technology/project details, fuel costs and corridors.</li><li><strong>Add a rule only when data is insufficient.</strong> Custom build-limit constraints alter the feasible investment set.</li><li><strong>Connect a new subsystem deliberately.</strong> New hydrogen decisions must participate in electricity balances, objective costs/revenues, physical constraints and output reporting.</li></ol><div className="callout">Your bottom-up residential demand model remains an optional example. Supplying externally computed load profiles can be a data or soft-link extension. Asking SWITCH to choose retrofits, equipment or flexible thermal operation requires additional decisions and constraints.</div><p><a href="https://github.com/NotEleven/Switch-Kenya-2025_public/tree/089834b8fee23239d61ffb6e7d68279f0a74efed" target="_blank" rel="noreferrer">Read the pinned Kenya source <ArrowUpRight size={14}/></a> · <a href="https://github.com/switch-model/switch/tree/239d62cbe9baeec3bb05e56487241bdea60740af" target="_blank" rel="noreferrer">Read the pinned core source <ArrowUpRight size={14}/></a></p></article>}
 </div>;}
